pull_requests:
  do_not_increment_build_number: false
image: Visual Studio 2019
configuration: Release
before_build:
  - nuget restore
build:
  parallel: true
  project: vMenu.sln
  include_nuget_references: true
  verbosity: minimal

deploy:
  - provider: GitHub
    release: "[Release] vMenu $(VERSION_NAME)"
    tag: $(VERSION_NAME)
    artifact: vMenu-$(VERSION_NAME).zip
    draft: true
    prerelease: false
    auth_token: $(github_auth)
    on:
      APPVEYOR_REPO_TAG: true
    description: "vMenu version $(VERSION_NAME)."
on_success:
  - cmd: appveyor/on_success.bat
on_failure:
  - cmd: appveyor/on_failure.bat
